storaging/settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("warehouses/", include("warehouses.urls")),
]

storaging/warehouses/urls.py
from django.urls import path
from . import views

app_name = "warehouses"

urlpatterns = [
    path(
        '',
        views.index_view,
        name='index'),
    path(
        "warehouse_list/",
        views.WarehouseListView.as_view(),
        name="warehouse_list",
    ),
    path(
        "create_warehouse/",
        views.WarehouseCreateView.as_view(),
        name="create_warehouse",
    ),
    path(
        "storagetype_list/",
        views.StorageTypeListView.as_view(),
        name="storagetype_list",
    ),
    path(
        "cargo_list/",
        views.CargoListView.as_view(),
        name="cargo_list",
    ),
    path(
        "warehouse_detail/<int:pk>/",
        views.WarehouseDetailView.as_view(),
        name="warehouse_detail",
    ),
    path(
        "storagetype_detail/<int:pk>/",
        views.StorageTypeDetailView.as_view(),
        name="storagetype_detail",
    ),
    path(
        "cargo_detail/<int:pk>/",
        views.CargoDetailView.as_view(),
        name="cargo_detail",
    ),
    path(
        "create_cargo/",
        views.CargoCreateView.as_view(),
        name="create_cargo",
    ),
    path(
        "create_storagetype/",
        views.StorageTypeCreateView.as_view(),
        name="create_storagetype",
    ),
    path(
        "update_cargo/<int:pk>/",
        views.CargoUpdateView.as_view(),
        name="update_cargo",
    ),
    path(
        "delete_cargo/<int:pk>/",
        views.CargoDeleteView.as_view(),
        name="delete_cargo",
    ),
    path(
        "update_storagetype/<int:pk>/",
        views.StorageTypeUpdateView.as_view(),
        name="update_storagetype",
    ),
    path(
        "delete_storagetype/<int:pk>/",
        views.StorageTypeDeleteView.as_view(),
        name="delete_storagetype",
    ),
    path(
        "update_warehouse/<int:pk>/",
        views.WarehouseTypeUpdateView.as_view(),
        name="update_warehouse",
    ),
    path(
        "delete_warehouse/<int:pk>/",
        views.WarehouseDeleteView.as_view(),
        name="delete_warehouse",
    )
]

storaging/warehouses/models.py
from django.db import models


class Warehouse(models.Model):
    name = models.CharField('Наименование склада', max_length=64, db_index=True)
    address = models.CharField('Адрес', max_length=150, null=False)
    description = models.CharField('Описание', max_length=150, null=True, blank=True)
    useful_value = models.FloatField('Площадь', null=False)

    class Meta:
        verbose_name = 'Склад'
        verbose_name_plural = 'Склады'


class StorageType(models.Model):
    name = models.CharField('Наименование типа хранения', max_length=64, db_index=True)
    description = models.CharField('Описание', max_length=150, null=True, blank=True)
    storage_value = models.FloatField('Вместимость')
    warehouse = models.ManyToManyField('Warehouse', verbose_name='Склад')

    class Meta:
        verbose_name = 'Тип хранения'
        verbose_name_plural = 'Типы хранения'


class Cargo(models.Model):
    name = models.CharField('Наименование груза', max_length=64, db_index=True)
    description = models.CharField('Описание', max_length=150, null=True, blank=True)
    cargo_value = models.FloatField('Объем груза')
    cargo_weight = models.FloatField('Вес груза')
    storage_type = models.ForeignKey(StorageType, verbose_name='Тип хранения', on_delete=models.CASCADE)
    warehouse = models.ForeignKey(Warehouse, verbose_name='Склад', on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'Груз'
        verbose_name_plural = 'Грузы'


class Quotes(models.Model):
    author = models.CharField('Автор', max_length=150, db_index=True)
    quote = models.CharField('Описание', max_length=1000, null=True, blank=True)

    class Meta:
        verbose_name = 'Цитата'
        verbose_name_plural = 'Цитаты'

storaging/warehouses/forms.py
from django import forms
from .models import Warehouse, StorageType, Cargo
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class WarehouseForm(forms.ModelForm):
    class Meta:
        model = Warehouse
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save warehouse'))


class StorageTypeForm(forms.ModelForm):
    class Meta:
        model = StorageType
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save storage type'))


class CargoForm(forms.ModelForm):
    class Meta:
        model = Cargo
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save cargo'))

storaging/warehouses/views.py
from django.urls import reverse_lazy

from .models import Warehouse, StorageType, Cargo
from .forms import WarehouseForm, StorageTypeForm, CargoForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import render

import logging

logger = logging.getLogger(__name__)


def index_view(request):

    return render(
        request,
        "warehouses/index.html",
        # context,
    )


class WarehouseListView(ListView):
    model = Warehouse


class WarehouseDetailView(DetailView):
    model = Warehouse


class WarehouseCreateView(CreateView):
    model = Warehouse
    form_class = WarehouseForm
    success_url = reverse_lazy('warehouses:warehouse_list')

    def form_valid(self, form):
        data = form.cleaned_data
        return super().form_valid(form)


class WarehouseTypeUpdateView(UpdateView):
    model = Warehouse
    fields = ('name', 'description')
    success_url = reverse_lazy('warehouses:warehouse_list')


class WarehouseDeleteView(DeleteView):
    model = Warehouse
    success_url = reverse_lazy('warehouses:warehouse_list')


class StorageTypeListView(ListView):
    model = StorageType


class StorageTypeDetailView(DetailView):
    model = StorageType


class StorageTypeCreateView(CreateView):
    model = StorageType
    form_class = StorageTypeForm
    success_url = reverse_lazy('warehouses:storagetype_list')

    def form_valid(self, form):
        data = form.cleaned_data
        return super().form_valid(form)


class StorageTypeUpdateView(UpdateView):
    model = StorageType
    fields = ('name', 'description')
    success_url = reverse_lazy('warehouses:storagetype_list')


class StorageTypeDeleteView(DeleteView):
    model = StorageType
    success_url = reverse_lazy('warehouses:storagetype_list')


class CargoListView(ListView):
    model = Cargo


class CargoDetailView(DetailView):
    model = Cargo


class CargoCreateView(CreateView):
    model = Cargo
    form_class = CargoForm
    success_url = reverse_lazy('warehouses:cargo_list')

    def form_valid(self, form):
        data = form.cleaned_data
        return super().form_valid(form)


class CargoUpdateView(UpdateView):
    model = Cargo
    fields = ('name', 'description', 'cargo_value', 'cargo_weight')
    success_url = reverse_lazy('warehouses:cargo_list')


class CargoDeleteView(DeleteView):
    model = Cargo
    success_url = reverse_lazy('warehouses:cargo_list')

storaging/warehouses/templates/warehouses/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% block body %}
    Base body
{% endblock %}

</body>
  {% include './quote_of_the_day.html' %}
  {% include './common_footer.html' %}
</html>

storaging/warehouses/templates/warehouses/cargo_confirm_delete.html
{% extends './base.html' %}
{% block title %}

<h3 class="p-15">Подтверждение удаления</h3>
{% endblock %}


{% block body %}
  <form method="post" class="border border-warning">
  <h1>Груз {{object.name}} будет удален из списка грузов</h1>

    {% csrf_token %}
  <div class="p-5 col-6" style="font-size: 1.5em">
<p>Продолжить удаление?
            </div>

      <div class="col-6 p-5">
          <p><button class="btn btn-primary" type="submit" style="font-size: 1.2em">Да</button>
        </div>
        <a class="p-5 m-5" style="font-size: 1.2em" href="{% url 'warehouses:cargo_list' %}">Вернуться к списку</a>
    </form>
{% endblock %}

storaging/warehouses/templates/warehouses/cargo_detail.html
{% extends './base.html' %}
{% block title %}

<h3 class="p-5">{{object.name}}</h3>
{% endblock %}

{% block body %}
<style>
    #form {
      padding: 5% 10%;
      margin: 6%;
      font-size: 1.5em;
    }
  </style>
{% load crispy_forms_tags %}

<div class="card text-left" >
  <form class="border border-primary">
    {% csrf_token %}
<div>

  <div class="p-5" style="font-size: 1.5em">
    <div class="col-6 p-2">
<span >
  На складе: {{object.warehouse.name}}
</span>
            </div>

      <div class="col-6 p-2">
      <span >
  Тип хранения: {{object.storage_type.name}}
</span>
        </div>

      <div class="col-6 p-2">
        Описание: {{object.description}}
      </div>
    </div>
</div>
      <div class="col-6 p-5">
    <a class="nav-link" aria-current="page" href="{% url 'warehouses:delete_cargo' pk=object.pk %}">Удалить груз?</a>
      </div>
  </form>

          <a class='p-5' href="{% url 'warehouses:cargo_list' %}">Вернуться к списку</a>
    </div>

{% endblock %}

storaging/warehouses/templates/warehouses/cargo_list.html
{% extends './base.html' %}

{% block body %}
  <h1 class="p-3">Грузы:</h1>
  {% if object_list %}
    <ul style="font-size: 1.5em" class="border border-primary p-5">
      {% for type in object_list %}
        <li class="m-3">
          <strong>{{ type.name }} (тип хранения: {{type.storage_type.name}})</strong>
          <strong>
            <a href="{% url 'warehouses:cargo_detail' pk=type.pk %}">
Подробнее            </a>
               </strong>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2 style="font-size: 1.5em" class="border border-primary p-5">Пока нет ни одного груза</h2>
  {% endif %}
<div>
    <ul class="nav flex-column" style="font-size: 1.2em">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'warehouses:create_cargo' %}">Добавить новый груз</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'warehouses:index' %}">Назад</a>
  </li>
</ul>
</div>

{% endblock %}

storaging/warehouses/templates/warehouses/common_footer.html
<div class="container my-5">

  <footer class="text-center text-white" style="background-color: #caced1;">
    <div class="container p-4">
      <section class="">
        <div class="row">
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              <img
                   src="https://mdbootstrap.com/img/new/fluid/city/113.jpg"
                   class="w-100"
                   />
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              <img
                   src="https://mdbootstrap.com/img/new/fluid/city/111.jpg"
                   class="w-100"
                   />
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              <img
                   src="https://mdbootstrap.com/img/new/fluid/city/112.jpg"
                   class="w-100"
                   />
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              <img
                   src="https://mdbootstrap.com/img/new/fluid/city/114.jpg"
                   class="w-100"
                   />
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              <img
                   src="https://mdbootstrap.com/img/new/fluid/city/115.jpg"
                   class="w-100"
                   />
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              <img
                   src="https://mdbootstrap.com/img/new/fluid/city/116.jpg"
                   class="w-100"
                   />
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
        </div>
      </section>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
  </footer>

</div>

storaging/warehouses/templates/warehouses/index.html
{% extends './base.html' %}


{% block body %}
  <h1 class="p-3">Склады: складские операции</h1>

<div class="card text-center d-grid gap-10 p-3" style="background-color: #f8f9fa;">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs" style="font-size: 1.2em">
      <li class="nav-item">
        <a class="nav-link" href="warehouse_list">Список складов</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="storagetype_list">Список типов хранения</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="cargo_list">Список грузов</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h5 class="card-title">Создать новый склад</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="create_warehouse" class="btn btn-primary">Создать</a>
  </div>
    <div class="card-body">
    <h5 class="card-title">Создать новый тип хранения</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="create_storagetype" class="btn btn-primary">Создать</a>
  </div>
    <div class="card-body">
    <h5 class="card-title">Создать новый груз</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="create_cargo" class="btn btn-primary">Создать</a>
  </div>
</div>

{% endblock %}

storaging/warehouses/templates/warehouses/quote_of_the_day.html
{% load quote_of_the_day %}

  <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>

  </head>

<div class="container my-5" style="
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;">
    <div class="card p-3 m-5 text-center" style="width: 25rem;">
  <div class="card-body">
    <p class="card-text">
        <h1>Давайте подумаем о жизни с цитатой дня</h1>
      <b>Сегодняшняя цитата: {% quote_of_the_day %}<label id="lucky"></label></b>
  </div>
</div>

</div>

storaging/warehouses/templates/warehouses/storagetype_confirm_delete.html
{% extends './base.html' %}

{% block title %}

<h3 class="p-15">Подтверждение удаления</h3>
{% endblock %}


{% block body %}
  <form method="post" class="border border-warning">
  <h1>Тип хранения {{object.name}} будет удален из списка типов хранения</h1>

    {% csrf_token %}
  <div class="p-5 col-6" style="font-size: 1.5em">
<p>Продолжить удаление?
            </div>

      <div class="col-6 p-5">
          <p><button class="btn btn-primary" type="submit" style="font-size: 1.2em">Да</button>
        </div>
        <a class="p-5 m-5" style="font-size: 1.2em" href="{% url 'warehouses:storagetype_list' %}">Вернуться к списку</a>
    </form>

{% endblock %}

storaging/warehouses/templates/warehouses/storagetype_form.html
{% extends './base.html' %}

{% block title %}
<h3 class="p-5">Создать новый тип хранения</h3>
{% endblock %}

{% block body %}
<style>
    #form {
      padding: 5% 10%;
      margin: 6%;
      font-size: 1.5em;
    }
  </style>
{% load crispy_forms_tags %}

{% block content %}
<div class="card text-left" >
  <form method="post" id="form" class="border border-primary">
    {% csrf_token %}
    {{ form|crispy }}
   <button class="btn btn-primary" type="submit">Создать</button>
  </form>
        <a class="p-3" style="font-size: 1.5em" href="{% url 'warehouses:storagetype_list' %}">Вернуться к списку</a>
    </div>

{% endblock %}


{% endblock %}

storaging/warehouses/templates/warehouses/storagetype_list.html
{% extends './base.html' %}

{% block body %}
  <h1 class="p-3">Типы хранения:</h1>
  {% if object_list %}
    <ul style="font-size: 1.5em" class="border border-primary p-5">
      {% for type in object_list %}
        <li class="m-3">
          <strong>{{ type.name }}</strong> <em>(
            {% for wh in type.warehouse.prefetch_related %}
             {{wh.name}}
                  {% endfor %}

            )</em>.
          <strong>
            <a href="{% url 'warehouses:storagetype_detail' pk=type.pk %}">
Подробнее            </a>
               </strong>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2 style="font-size: 1.5em" class="border border-primary p-5">Пока нет типов хранения</h2>
  {% endif %}
<div>
    <ul class="nav flex-column" style="font-size: 1.2em">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'warehouses:create_storagetype' %}">Добавить новый тип хранения</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'warehouses:index' %}">Назад</a>
  </li>
</ul>
</div>

{% endblock %}

storaging/warehouses/templates/warehouses/warehouse_confirm_delete.html
{% extends './base.html' %}

{% block title %}

<h3 class="p-15">Подтверждение удаления</h3>
{% endblock %}


{% block body %}
  <form method="post" class="border border-warning">
  <h1>Склад {{object.name}} будет удален из списка складов</h1>

    {% csrf_token %}
  <div class="p-5 col-6" style="font-size: 1.5em">
<p>Продолжить удаление?
            </div>

      <div class="col-6 p-5">
          <p><button class="btn btn-primary" type="submit" style="font-size: 1.2em">Да</button>
        </div>
        <a class="p-5 m-5" style="font-size: 1.2em" href="{% url 'warehouses:warehouse_list' %}">Вернуться к списку</a>
    </form>
{% endblock %}

storaging/warehouses/templates/warehouses/warehouse_detail.html
{% extends './base.html' %}

{% block title %}

<h3 class="p-5">{{object.name}}</h3>
{% endblock %}

{% block body %}
<style>
    #form {
      padding: 5% 10%;
      margin: 6%;
      font-size: 1.5em;
    }
  </style>
{% load crispy_forms_tags %}

<div class="card text-left" >
  <form class="border border-primary">
    {% csrf_token %}
<div>

  <div class="p-5" style="font-size: 1.5em">
    <div class="col-6 p-2">
<span >
  Площадь склада: {{object.useful_value}}
</span>
            </div>

      <div class="col-6 p-2">
      <span >
</span>
        </div>

      <div class="col-6 p-2">
        Описание: {{object.description}}
      </div>
    </div>
</div>
      <div class="col-6 p-5">
    <a class="nav-link" aria-current="page" href="{% url 'warehouses:delete_warehouse' pk=object.pk %}">Удалить склад?</a>
      </div>
  </form>

          <a class='p-5' href="{% url 'warehouses:warehouse_list' %}">Вернуться к списку</a>
    </div>

{% endblock %}

storaging/warehouses/templates/warehouses/warehouse_form.html
{% extends './base.html' %}

{% block title %}
<h3 class="p-5">Создать новый склад</h3>
{% endblock %}

{% block body %}
<style>
    #form {
      padding: 5% 10%;
      margin: 6%;
      font-size: 1.5em;
    }
  </style>
{% load crispy_forms_tags %}

{% block content %}
<div class="card text-left" style="background-color: #f8f9fa;" >
  <form method="post" id="form" class="border border-primary">
    {% csrf_token %}
    {{ form|crispy }}
   <button class="btn btn-primary" type="submit">Создать</button>
  </form>
        <a class="p-3" style="font-size: 1.5em" href="{% url 'warehouses:warehouse_list' %}">Вернуться к списку</a>
    </div>

{% endblock %}


{% endblock %}

storaging/warehouses/templates/warehouses/warehouse_list.html
{% extends './base.html' %}

{% block body %}
  <h1 class="p-3">Склады:</h1>
  {% if object_list %}
    <ul style="font-size: 1.5em; background-color: #f8f9fa;" class="border border-primary p-5">
      {% for type in object_list %}
        <li class="m-3">
          <strong>{{ type.name }}</strong> <em>({{ type.address }})</em>.
          <strong>
            <a href="{% url 'warehouses:warehouse_detail' pk=type.pk %}">
Подробнее            </a>
               </strong>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2 style="font-size: 1.5em; background-color: #f8f9fa;" class="border border-primary p-5">Пока нет складов</h2>
  {% endif %}
<div>
    <ul class="nav flex-column" style="font-size: 1.2em">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'warehouses:create_warehouse' %}">Добавить новый склад</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'warehouses:index' %}">Назад</a>
  </li>
</ul>
</div>
{% endblock %}